package model

// cultivation
type Culti struct {
	tableName      struct{} `sql:"user_girl"`
	UserId         Uid
	GirlId         Gid
	Ranks          []int `pg:",array"`
	AvgPoint       float64
	ATop           int
	ALast          int
	Round          int
	Win            int
	Gun            int
	Bark           int
	Riichi         int
	WinPoint       float64
	GunPoint       float64
	BarkPoint      float64
	RiichiPoint    float64
	Ready          int
	ReadyTurn      float64
	WinTurn        float64
	YakuRci        int
	YakuIpt        int
	YakuTmo        int
	YakuTny        int
	YakuPnf        int
	YakuY1y        int
	YakuY2y        int
	YakuY3y        int
	YakuJk1        int
	YakuJk2        int
	YakuJk3        int
	YakuJk4        int
	YakuBk1        int
	YakuBk2        int
	YakuBk3        int
	YakuBk4        int
	YakuIpk        int
	YakuRns        int
	YakuHai        int
	YakuHou        int
	YakuCkn        int
	YakuSs1        int
	YakuIt1        int
	YakuCt1        int
	YakuWri        int
	YakuSs2        int
	YakuIt2        int
	YakuCt2        int
	YakuToi        int
	YakuCtt        int
	YakuSak        int
	YakuSkt        int
	YakuStk        int
	YakuHrt        int
	YakuS3g        int
	YakuH1t        int
	YakuJc2        int
	YakuMnh        int
	YakuJc3        int
	YakuRpk        int
	YakuC1t        int
	YakuMnc        int
	YakuX13        int
	YakuXd3        int
	YakuX4a        int
	YakuXt1        int
	YakuXs4        int
	YakuXd4        int
	YakuXcr        int
	YakuXr1        int
	YakuXth        int
	YakuXch        int
	YakuX4k        int
	YakuX9r        int
	YakuW13        int
	YakuW4a        int
	YakuW9r        int
	Kzeykm         int
	HanRci         float64
	HanIpt         float64
	HanTmo         float64
	HanTny         float64
	HanPnf         float64
	HanY1y         float64
	HanY2y         float64
	HanY3y         float64
	HanJk1         float64
	HanJk2         float64
	HanJk3         float64
	HanJk4         float64
	HanBk1         float64
	HanBk2         float64
	HanBk3         float64
	HanBk4         float64
	HanIpk         float64
	HanRns         float64
	HanHai         float64
	HanHou         float64
	HanCkn         float64
	HanSs1         float64
	HanIt1         float64
	HanCt1         float64
	HanWri         float64
	HanSs2         float64
	HanIt2         float64
	HanCt2         float64
	HanToi         float64
	HanCtt         float64
	HanSak         float64
	HanSkt         float64
	HanStk         float64
	HanHrt         float64
	HanS3g         float64
	HanH1t         float64
	HanJc2         float64
	HanMnh         float64
	HanJc3         float64
	HanRpk         float64
	HanC1t         float64
	HanMnc         float64
	YakuDora       int
	YakuUradora    int
	YakuAkadora    int
	YakuKandora    int
	YakuKanuradora int
}

type EndTableStat struct {
	Ranks           [4]int
	Points          [4]int
	ATop            bool
	ALast           bool
	Round           int
	Wins            [4]int
	Guns            [4]int
	Barks           [4]int
	Riichis         [4]int
	WinSumPoints    [4]int
	GunSumPoints    [4]int
	BarkSumPoints   [4]int
	RiichiSumPoints [4]int
	ReadySumTurns   [4]int
	Readys          [4]int
	WinSumTurns     [4]int
	Yakus           [4]map[string]int
	SumHans         [4]map[string]int
	Kzeykms         [4]int
	Replay          map[string]interface{}
}
